### ISSUE TITLE
Filebeat / prometheus support?

### ISSUE THREAD

**Issue by w3s7y** [nolte/ansible-minecraft#57]
First of all, thanks for a solid vanilla module.  This is not a bug report.

This was useful to me personally and I'd like to repay with some basic filebeat install/setup for your role.

Is this something you would be interested in?   

Thanks,
Ben

p.s. If you are interested.. [My terraform/ansible implementation](https://github.com/w3s7y/minecraft-server)

**Comment by nolte** [comment]
Hi, 
First, Thanks for the nice Feedback!

What did you meen with "basic filebeat install/setup", i think the best way for integrate a FileBeat is using a second role like [geerlingguy/filebeat](https://galaxy.ansible.com/geerlingguy/filebeat), the same with a Prometheus Node Exporter.

For the Minecraft Prometheus Integration you can use [sladkoff/minecraft-prometheus-exporter](https://github.com/sladkoff/minecraft-prometheus-exporter), this can be install with the Role Plugin Configuration. 

A change for this Role can be, a feature flag for a [gelf](https://docs.graylog.org/en/3.1/pages/gelf.html) integration, so you can send the Server Logs direct over tcp/udp to our Logstash Instance. This needs a Configurable Log4j Config and a addition jar in the Server Class Path.

I Like your AWS Terraform Sources,  if it is ok, i will Link it from This Repo, and put a Comment to my Infrastructure Repository [nolte/minecraft-infrastructure](https://github.com/nolte/minecraft-infrastructure).
